# Generated by Django 3.1.6 on 2021-03-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20210326_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfiles',
            name='file_type',
            field=models.CharField(default='video', max_length=500),
            preserve_default=False,
        ),
    ]
