# Generated by Django 3.1.6 on 2021-04-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_hashtag_posthashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='google_event_id',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
