# Generated by Django 3.1.6 on 2021-04-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20210409_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
