# Generated by Django 3.1.6 on 2021-04-09 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('timeline', '0013_auto_20210409_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='google_event_id',
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_reviews', to='schedule.order'),
        ),
    ]
