# Generated by Django 3.1.6 on 2021-04-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_auto_20210409_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='accepted', max_length=255),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='status',
            field=models.CharField(default='accepted', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(default='accepted', max_length=255),
        ),
    ]
