# Generated by Django 3.1.6 on 2021-12-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0024_tarif_is_deleted'),
        ('timeline', '0017_reportpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.service'),
        ),
    ]
