# Generated by Django 3.1.6 on 2022-02-14 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0018_post_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply',
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.review'),
        ),
    ]
