# Generated by Django 3.1.6 on 2022-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_parent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
