# Generated by Django 2.1 on 2021-02-05 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0003_auto_20210205_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_certificates', to='userdetails.UserDetail'),
        ),
        migrations.AlterField(
            model_name='mastercreditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdetails.UserDetail'),
        ),
        migrations.AlterField(
            model_name='masterservice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_services', to='userdetails.UserDetail'),
        ),
        migrations.AlterField(
            model_name='masterworkphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_work_photo', to='userdetails.UserDetail'),
        ),
    ]
