# Generated by Django 2.1 on 2021-02-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0004_auto_20210205_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercreditcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_credit_cards', to='userdetails.UserDetail'),
        ),
    ]
