# Generated by Django 3.1.6 on 2021-02-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0006_auto_20210212_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
