# Generated by Django 3.1.6 on 2021-03-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_tarif_category_count'),
        ('userdetails', '0011_tarifcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.tarif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='userdetails.userdetail')),
            ],
        ),
    ]
