# Generated by Django 3.1.6 on 2021-03-27 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0012_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='master_tarif_subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='userdetails.mastertarifsubscribtion'),
            preserve_default=False,
        ),
    ]
