# Generated by Django 3.1.6 on 2021-04-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0013_auto_20210327_1055'),
    ]

