# Generated by Django 3.1.6 on 2021-04-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0014_remove_transaction_tatif'),
    ]

