# Generated by Django 3.1.6 on 2021-04-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0016_userdetail_google_calendar_id'),
    ]
