# Generated by Django 3.1.6 on 2021-04-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0021_auto_20210409_1221'),
    ]
