# Generated by Django 3.1.6 on 2021-04-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0022_auto_20210409_1606'),
    ]
