# Generated by Django 3.1.6 on 2021-04-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0023_auto_20210409_1624'),
    ]
