# Generated by Django 3.1.6 on 2021-04-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0025_auto_20210414_1526'),
    ]
