# Generated by Django 3.1.6 on 2021-04-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0026_auto_20210414_1621'),
    ]
