# Generated by Django 3.1.6 on 2021-04-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0027_auto_20210414_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='stripe_client_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
