# Generated by Django 3.1.6 on 2021-04-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0031_auto_20210420_1026'),
    ]

