# Generated by Django 3.1.6 on 2021-04-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0032_remove_transaction_tarif'),
    ]

