# Generated by Django 3.1.6 on 2021-04-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_city_country'),
        ('userdetails', '0033_remove_transaction_tarif'),
    ]

    operations = [
    ]
