# Generated by Django 3.1.6 on 2021-04-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0034_auto_20210423_1002'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='userdetail',
            name='city',
        ),
    ]
