# Generated by Django 3.1.6 on 2021-04-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_city_country'),
        ('userdetails', '0035_auto_20210423_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.city'),
        ),
    ]
