# Generated by Django 3.1.6 on 2021-04-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_city_country'),
        ('userdetails', '0036_auto_20210423_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='city_masters', to='utils.city'),
        ),
    ]
