# Generated by Django 3.1.6 on 2021-04-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0038_auto_20210426_1308'),
    ]

