# Generated by Django 3.1.6 on 2021-05-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0040_auto_20210519_1431'),
    ]

    operations = [

        migrations.AddField(
            model_name='userdetail',
            name='is_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
