# Generated by Django 3.1.6 on 2021-05-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0041_auto_20210525_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tarif',
        ),
    ]
