# Generated by Django 3.1.6 on 2021-09-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0042_remove_transaction_tarif'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_favorite_users', to='userdetails.userdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_masters', to='userdetails.userdetail')),
            ],
        ),
    ]
