# Generated by Django 3.1.6 on 2021-11-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0044_auto_20211015_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
