# Generated by Django 3.1.6 on 2022-04-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0025_auto_20220118_1621'),
        ('userdetails', '0047_remove_userdetail_push_token'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterservice',
            unique_together={('user', 'service')},
        ),
    ]
