# Generated by Django 3.1.6 on 2022-05-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0048_auto_20220411_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterservice',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
