# Generated by Django 3.1.6 on 2021-04-09 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0015_tarif_is_active'),
        ('userdetails', '0022_auto_20210409_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=500, null=True)),
                ('google_event_id', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_orders', to='userdetails.userdetail')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='userdetails.userdetail')),
            ],
        ),
    ]
