# Generated by Django 3.1.6 on 2021-04-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0026_auto_20210414_1621'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_prepayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='prepayed_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=255, null=True)),
                ('refunded_amount', models.FloatField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to='userdetails.userdetail')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_transactions', to='userdetails.userdetail')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.order')),
            ],
        ),
    ]
