# Generated by Django 3.1.6 on 2021-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210414_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prepayed_status',
            field=models.CharField(blank=True, default='pending', max_length=255, null=True),
        ),
    ]
