# Generated by Django 3.1.6 on 2021-06-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
