# Generated by Django 3.1.6 on 2021-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210625_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='go_home',
            field=models.BooleanField(default=False),
        ),
    ]
