# Generated by Django 3.1.6 on 2021-11-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_historicalorder_historicaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
