# Generated by Django 3.1.6 on 2021-11-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20211101_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
