# Generated by Django 3.1.6 on 2021-11-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20211101_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalOrder',
        ),
    ]
