# Generated by Django 2.1 on 2021-02-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_timetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeType',
        ),
    ]
