# Generated by Django 3.1.6 on 2021-02-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_delete_timetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
