# Generated by Django 3.1.6 on 2021-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
