# Generated by Django 3.1.6 on 2021-03-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_category_is_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
