# Generated by Django 3.1.6 on 2021-03-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=50),
        ),
    ]
