# Generated by Django 3.1.6 on 2021-03-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_auto_20210326_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
        ),
    ]
