# Generated by Django 3.1.6 on 2021-03-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_auto_20210326_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='category_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
