# Generated by Django 3.1.6 on 2021-04-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_tarif_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='price',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=50),
        ),
    ]
