# Generated by Django 3.1.6 on 2021-10-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
