# Generated by Django 3.1.6 on 2021-11-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
