# Generated by Django 3.1.6 on 2021-11-29 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_departement_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.departement'),
        ),
    ]
