# Generated by Django 3.1.6 on 2021-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_city_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
