# Generated by Django 3.1.6 on 2022-01-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0024_tarif_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
        ),
    ]
