# Generated by Django 3.1.6 on 2022-07-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0028_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
