# Generated by Django 3.1.6 on 2022-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0033_remove_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
