# Generated by Django 3.1.6 on 2022-07-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0034_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
