# Generated by Django 3.1.6 on 2021-04-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('for_users', models.PositiveIntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('for_users', models.PositiveIntegerField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
