# Generated by Django 3.1.6 on 2021-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='text',
        ),
        migrations.RemoveField(
            model_name='schedulednotification',
            name='text',
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='text_en',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='text_fr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='text_en',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='schedulednotification',
            name='text_fr',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
