# Generated by Django 3.1.6 on 2021-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210422_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('text_en', models.TextField(default='')),
                ('text_fr', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('text_en', models.TextField(default='')),
                ('text_fr', models.TextField(default='')),
            ],
        ),
    ]
