# Generated by Django 3.1.6 on 2021-05-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0040_auto_20210519_1431'),
        ('utils', '0016_city_country'),
        ('schedule', '0004_order_created_at'),
        ('notifications', '0005_auto_20210426_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPushNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('fullname_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdetails.userdetail')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.notificationtype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.order')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utils.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scheduled_notifications', to='userdetails.userdetail')),
            ],
        ),
    ]
