# Generated by Django 3.1.6 on 2021-06-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_scheduledpushnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
