# Generated by Django 3.1.6 on 2021-06-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_notification_scheduled_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='subject_en',
            field=models.CharField(default='  ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledemail',
            name='subject_fr',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
