# Generated by Django 3.1.6 on 2021-06-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20210603_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='scheduled_notif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sch_notifs', to='notifications.schedulednotification'),
        ),
    ]
