# Generated by Django 3.1.6 on 2022-01-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notification_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='text_example',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
