# Generated by Django 3.1.6 on 2022-02-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_notificationtype_text_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtypes',
            name='subject',
            field=models.CharField( max_length=255),
            preserve_default=False,
        ),
    ]
