# Generated by Django 3.1.6 on 2022-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20220211_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtypes',
            name='subject_example',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emailtypes',
            name='text_example',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
